# Generated by Django 4.2.3 on 2023-09-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
