# Generated by Django 4.2.3 on 2023-09-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_perro_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='foto',
        ),
    ]
